export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const ORDER_BY_ASCDESC_PRICE = "ORDER_BY_ASCDESC_PRICE";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CATEGORIES_PRODUCT = "CATEGORIES_PRODUCT";
export const SORTED_PRICE_PRODUCTS = "SORTED_PRICE_PRODUCTS";

